#include "GraphiteGlobals.hpp"
#include "../../RhythmAudio/RhythmAudio/RhythmAudioEngine.hpp"
#include "../../RhythmInput/RhythmInput/RhythmInputEngine.hpp"

std::optional<RhythmAudio::RhythmAudioEngine> GraphiteGlobals::audioEngine{std::nullopt};
std::optional<RhythmInput::RhythmInputEngine> GraphiteGlobals::inputEngine{std::nullopt};
uint64_t GraphiteGlobals::blueRyouHitsoundHandle{0};
uint64_t GraphiteGlobals::blueKaHitsoundHandle{0};
uint64_t GraphiteGlobals::blueFukaHitsoundHandle{0};
uint64_t GraphiteGlobals::blueChouHitsoundHandle{0};
uint64_t GraphiteGlobals::blueAdLibHitsoundHandle{0};
uint64_t GraphiteGlobals::redRyouHitsoundHandle{0};
uint64_t GraphiteGlobals::redKaHitsoundHandle{0};
uint64_t GraphiteGlobals::redFukaHitsoundHandle{0};
uint64_t GraphiteGlobals::redChouHitsoundHandle{0};
uint64_t GraphiteGlobals::redAdLibHitsoundHandle{0};
uint64_t GraphiteGlobals::greenNoteCompleteHitsoundHandle{0};
LFProtectObj<Chart> GraphiteGlobals::currentChart{};
int64_t GraphiteGlobals::audioOffset{0};
int64_t GraphiteGlobals::visualOffset{0};
int32_t GraphiteGlobals::difficulty{0};
std::string GraphiteGlobals::currentSongFileName{""};
bool GraphiteGlobals::modVisualOffsetCalibration{false};
bool GraphiteGlobals::modAudioOffsetCalibration{false};
int32_t GraphiteGlobals::menuCurrentNodeId{-1};
int32_t GraphiteGlobals::menuCurrentItemIndex{0};
int32_t GraphiteGlobals::menuScrollOffset{0};
std::vector<int32_t> GraphiteGlobals::menuNavNodeIds{};
std::vector<int32_t> GraphiteGlobals::menuNavItemIndices{};
std::vector<int32_t> GraphiteGlobals::menuNavScrollOffsets{};